---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true


- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true