kubernetes_version: "1.28"
kubernetes_node_ip: "10.0.0.10"
kubernates_pod_network_cidr: "172.16.1.0/16"
kubernates_service_cidr: "172.17.1.0/18"
kubernetes_node_name: "master-node"

server_hosts:
    - ip_address: "10.0.0.10"
      host_name: "master-node"
    
    - ip_address: "10.0.0.11"
      host_name: "worker-node-01"
